const constants = {
  ADD_RECIPE = 'ADD_RECIPE',
  DELETE_RECIPE = 'DELETE_RECIPE',
  EDIT_RECIPE = 'EDIT_RECIPE',
  CHANGE_EDIT = 'CHANGE_EDIT',
  CHANGE_BUTTON = 'CHANGE_BUTTON',
  SHOW_MODAL = 'SHOW_MODAL',
  HIDE_MODAL = 'HIDE_MODAL',
  UPDATE_RECIPE_TEXT = 'UPDATE_RECIPE_TEXT',
  UPDATE_INGREDIENTS_TEXT = 'UPDATE_INGREDIENTS_TEXT',
}

export default constants